const help = (prefix) => { 
	return `
─────────────────────
═══ 《 *Galih Menu* 》 ═══
─────────────────────
-❥ *${prefix}sticker*
-❥ *${prefix}ocr*
-❥ *${prefix}stickergif*
-❥ *${prefix}stickergiphy*
-❥ *${prefix}slightning*
-❥ *${prefix}sfire*
-❥ *${prefix}meme*
-❥ *${prefix}quotemaker*
-❥ *${prefix}nulis*
-❥ *${prefix}stimg*
-❥ *${prefix}magernulis*
-❥ *${prefix}romancetext*
-❥ *${prefix}glitchtext*
-❥ *${prefix}lovemaker*
-❥ *${prefix}tahta [teks]*
-❥ *${prefix}ttp [teks]*
-❥ *${prefix}pornlogo [|teks1|teks2]*
-❥ *${prefix}blackpink [teks]*
-❥ *${prefix}epep*
-❥ *${prefix}gaming*
-❥ *${prefix}qrcode*
-❥ *${prefix}joker*
-❥ *${prefix}glowmaker*
-❥ *${prefix}thunder*
-❥ *${prefix}hideteks*
-❥ *${prefix}watercolour*
-❥ *${prefix}3dtext*
-❥ *${prefix}googleteks*
-❥ *${prefix}phcomment*
-❥ *${prefix}lion*
-❥ *${prefix}wolf*
-❥ *${prefix}wolf2*
-❥ *${prefix}silverpb*
-❥ *${prefix}goldpb*
-❥ *${prefix}logoml*
-❥ *${prefix}ninja*
-❥ *${prefix}valentine*
-❥ *${prefix}missing*
-❥ *${prefix}kapankah*
-❥ *${prefix}rate*
-❥ *${prefix}apakah*
-❥ *${prefix}bisakah*
-❥ *${prefix}dewabatch*
-❥ *${prefix}images*
-❥ *${prefix}sreddit*
-❥ *${prefix}resep*
-❥ *${prefix}stalkig*
-❥ *${prefix}wiki*
-❥ *${prefix}cuaca*
-❥ *${prefix}chord*
-❥ *${prefix}lirik*
-❥ *${prefix}ss*
-❥ *${prefix}movie*
-❥ *${prefix}whatanime*
-❥ *${prefix}google*
-❥ *${prefix}pinterest*
-❥ *${prefix}brainly*
-❥ *${prefix}math*
-❥ *${prefix}heroml*
-❥ *${prefix}kbbi*
-❥ *${prefix}shopee*
-❥ *${prefix}playstore*
-❥ *${prefix}news*
-❥ *${prefix}newstickerline*
-❥ *${prefix}jadwalbola*
-❥ *${prefix}jarak*
-❥ *${prefix}maps*
-❥ *${prefix}lk21*
-❥ *${prefix}dadu*
-❥ *${prefix}koin*
-❥ *${prefix}randomtag [pesan]*
-❥ *${prefix}bucin*
-❥ *${prefix}motivasi*
-❥ *${prefix}howgay*
-❥ *${prefix}fakta*
-❥ *${prefix}pantun*
-❥ *${prefix}katabijak*
-❥ *${prefix}quote*
-❥ *${prefix}cerpen*
-❥ *${prefix}puisi*
-❥ *${prefix}anime*
-❥ *${prefix}kpop*
-❥ *${prefix}memes*
-❥ *${prefix}loli*
-❥ *${prefix}shota*
-❥ *${prefix}waifu*
-❥ *${prefix}husbu*
-❥ *${prefix}baka*
-❥ *${prefix}neko*
-❥ *${prefix}truth*
-❥ *${prefix}dare*
-❥ *${prefix}groupinfo*
-❥ *${prefix}artinama*
-❥ *${prefix}cekjodoh*
-❥ *${prefix}add*
-❥ *${prefix}kick* @tag
-❥ *${prefix}promote* @tag
-❥ *${prefix}demote* @tag
-❥ *${prefix}gc [buka | tutup]*
-❥ *${prefix}tagall [pesan]*
-❥ *${prefix}setprofile*
-❥ *${prefix}delete*
-❥ *${prefix}welcome*
-❥ *${prefix}leave*
-❥ *${prefix}tts*
-❥ *${prefix}hidetag*`
}

exports.help = help
